// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnqNysOU21YSUmXr1nNjJXfgyN5jlsFXI',
    appId: '1:344313066775:web:f86f038354eb7f8a8db352',
    messagingSenderId: '344313066775',
    projectId: 'rossi-app-a7cf4',
    authDomain: 'rossi-app-a7cf4.firebaseapp.com',
    storageBucket: 'rossi-app-a7cf4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6Ud2mNJgV5vp59txA5t4RCOJSYSQYEO4',
    appId: '1:344313066775:android:88b3dacb93f6e5f78db352',
    messagingSenderId: '344313066775',
    projectId: 'rossi-app-a7cf4',
    storageBucket: 'rossi-app-a7cf4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM9D5dnaod1YexA00TOMIiziUw_pv1OVU',
    appId: '1:344313066775:ios:d4d5db53b9f675d28db352',
    messagingSenderId: '344313066775',
    projectId: 'rossi-app-a7cf4',
    storageBucket: 'rossi-app-a7cf4.firebasestorage.app',
    iosBundleId: 'com.example.rossiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDM9D5dnaod1YexA00TOMIiziUw_pv1OVU',
    appId: '1:344313066775:ios:d4d5db53b9f675d28db352',
    messagingSenderId: '344313066775',
    projectId: 'rossi-app-a7cf4',
    storageBucket: 'rossi-app-a7cf4.firebasestorage.app',
    iosBundleId: 'com.example.rossiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnqNysOU21YSUmXr1nNjJXfgyN5jlsFXI',
    appId: '1:344313066775:web:1bdd0373c39f11698db352',
    messagingSenderId: '344313066775',
    projectId: 'rossi-app-a7cf4',
    authDomain: 'rossi-app-a7cf4.firebaseapp.com',
    storageBucket: 'rossi-app-a7cf4.firebasestorage.app',
  );
}
